"""baseline: полная схема GradeSentinel на PostgreSQL (портирована с SQLite)

Финальное состояние схемы (после всех исторических in-code SQLite-миграций).
Целевая БД пустая → одна baseline-ревизия вместо переноса истории миграций.

Ключевые отличия от SQLite-DDL (миграция 2026-06-29):
  • INTEGER PRIMARY KEY AUTOINCREMENT → integer GENERATED BY DEFAULT AS IDENTITY;
  • 🔴 все Telegram-/chat-/thread-id → BIGINT (PG INTEGER 32-битный — переполнится);
  • timestamp-колонки = naive UTC, DEFAULT (now() at time zone 'utc');
  • boolean-как-int (is_used) оставлен INTEGER (минимум правок call-сайтов).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-29
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

# Наивный UTC по умолчанию: now() → timestamptz, AT TIME ZONE 'utc' даёт
# наивное настенное время UTC (стратегия дат, подтверждённая владельцем).
_UTC = "(now() at time zone 'utc')"

DDL = f"""
CREATE TABLE parents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio text NOT NULL,
    phone text UNIQUE NOT NULL,
    telegram_id bigint UNIQUE,
    role text DEFAULT 'senior',
    telegram_first_name text,
    notify_mode text DEFAULT 'instant',
    lang text DEFAULT 'ru'
);

CREATE TABLE families (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_name text NOT NULL,
    subscription_end timestamp,
    head_id integer REFERENCES parents(id)
);

CREATE TABLE students (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio text NOT NULL,
    spreadsheet_id text NOT NULL,
    display_name text
);

CREATE TABLE family_links (
    family_id integer REFERENCES families(id),
    parent_id integer REFERENCES parents(id),
    student_id integer REFERENCES students(id),
    UNIQUE(family_id, parent_id, student_id)
);

CREATE TABLE grade_history (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES students(id),
    subject text NOT NULL,
    grade_value real,
    raw_text text NOT NULL,
    cell_reference text NOT NULL,
    grade_date date NOT NULL,
    date_added timestamp DEFAULT {_UTC},
    UNIQUE(student_id, subject, grade_date, raw_text)
);

CREATE TABLE quarter_grades (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES students(id),
    subject text NOT NULL,
    quarter integer NOT NULL,
    grade_value real,
    raw_text text,
    updated_at timestamp DEFAULT {_UTC},
    UNIQUE(student_id, subject, quarter)
);

CREATE TABLE app_states (
    user_id bigint PRIMARY KEY,
    last_menu_msg_id bigint
);

CREATE TABLE user_states (
    user_id bigint PRIMARY KEY,
    state text NOT NULL,
    data text,
    updated_at timestamp DEFAULT {_UTC}
);

CREATE TABLE support_msg_map (
    admin_msg_id bigint PRIMARY KEY,
    user_id bigint NOT NULL
);

CREATE TABLE notification_queue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE group_notification_queue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id bigint NOT NULL,
    message_thread_id bigint,
    message text NOT NULL,
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE ai_chat_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id bigint NOT NULL,
    student_id integer,
    family_id integer,
    role text NOT NULL,
    content text NOT NULL,
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE ai_chat_feedback (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id integer NOT NULL UNIQUE REFERENCES ai_chat_messages(id) ON DELETE CASCADE,
    telegram_id bigint NOT NULL,
    rating integer NOT NULL,
    comment text,
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE proactive_alerts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    alert_type text NOT NULL,
    sent_at timestamp DEFAULT {_UTC}
);

CREATE TABLE family_invites (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id integer NOT NULL REFERENCES families(id),
    invite_code text UNIQUE NOT NULL,
    created_by integer NOT NULL REFERENCES parents(id),
    used_by integer,
    created_at timestamp DEFAULT {_UTC},
    expires_at timestamp,
    is_used integer DEFAULT 0
);

CREATE TABLE payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id integer NOT NULL REFERENCES families(id),
    telegram_payment_charge_id text,
    provider_payment_charge_id text,
    amount integer NOT NULL,
    currency text NOT NULL DEFAULT 'UZS',
    plan text NOT NULL DEFAULT 'basic',
    months integer NOT NULL DEFAULT 1,
    paid_by integer NOT NULL REFERENCES parents(id),
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE promo_codes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL,
    plan text NOT NULL,
    discount_percent integer NOT NULL DEFAULT 0,
    free_months integer NOT NULL DEFAULT 0,
    max_uses integer NOT NULL DEFAULT 1,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamp,
    created_at timestamp DEFAULT {_UTC}
);

CREATE TABLE family_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id integer NOT NULL REFERENCES families(id),
    chat_id bigint NOT NULL UNIQUE,
    chat_title text,
    message_thread_id bigint,
    added_by integer NOT NULL REFERENCES parents(id),
    added_at timestamp DEFAULT {_UTC}
);

CREATE TABLE grade_history_archive (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    subject text NOT NULL,
    grade_value real,
    raw_text text NOT NULL,
    cell_reference text NOT NULL,
    grade_date date,
    date_added timestamp NOT NULL,
    archived_at timestamp DEFAULT {_UTC}
);

CREATE INDEX idx_grade_history_student_date ON grade_history(student_id, date_added);
CREATE INDEX idx_grade_history_student_cell ON grade_history(student_id, cell_reference);
CREATE INDEX idx_grade_history_student_grade_date ON grade_history(student_id, grade_date);
CREATE INDEX idx_family_links_parent ON family_links(parent_id);
CREATE INDEX idx_family_links_student ON family_links(student_id);
CREATE INDEX idx_family_links_family ON family_links(family_id);
CREATE INDEX idx_parents_telegram ON parents(telegram_id);
CREATE INDEX idx_notification_queue_tg ON notification_queue(telegram_id);
CREATE INDEX idx_quarter_grades_student ON quarter_grades(student_id);
CREATE INDEX idx_ai_chat_tg_student ON ai_chat_messages(telegram_id, student_id, created_at);
CREATE INDEX idx_ai_chat_tg_family ON ai_chat_messages(telegram_id, family_id, created_at);
CREATE INDEX idx_ai_feedback_tg_created ON ai_chat_feedback(telegram_id, created_at);
CREATE INDEX idx_proactive_alerts_lookup ON proactive_alerts(student_id, alert_type, sent_at DESC);
CREATE INDEX idx_family_groups_family ON family_groups(family_id);
CREATE INDEX idx_grade_archive_student_date ON grade_history_archive(student_id, date_added);
"""

# Порядок DROP — обратный зависимостям FK.
_DROP = """
DROP TABLE IF EXISTS grade_history_archive CASCADE;
DROP TABLE IF EXISTS family_groups CASCADE;
DROP TABLE IF EXISTS promo_codes CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS family_invites CASCADE;
DROP TABLE IF EXISTS proactive_alerts CASCADE;
DROP TABLE IF EXISTS ai_chat_feedback CASCADE;
DROP TABLE IF EXISTS ai_chat_messages CASCADE;
DROP TABLE IF EXISTS group_notification_queue CASCADE;
DROP TABLE IF EXISTS notification_queue CASCADE;
DROP TABLE IF EXISTS support_msg_map CASCADE;
DROP TABLE IF EXISTS user_states CASCADE;
DROP TABLE IF EXISTS app_states CASCADE;
DROP TABLE IF EXISTS quarter_grades CASCADE;
DROP TABLE IF EXISTS grade_history CASCADE;
DROP TABLE IF EXISTS family_links CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS families CASCADE;
DROP TABLE IF EXISTS parents CASCADE;
"""


def upgrade():
    op.execute(DDL)


def downgrade():
    op.execute(_DROP)
