"""student_years — класс и таблица ученика по учебным годам

Оценки за прошлый класс никуда не деваются (история привязана к student_id),
но посмотреть их «как за 8 класс» было нельзя: класс и ссылка на таблицу
хранятся одним полем в `students` и перезаписываются при смене ссылки. Ученик
переходит в 9 класс — и прошлогодние оценки подписываются «9 Orion».

Таблица хранит по одному снимку на учебный год: какой был класс и какая
таблица. Это же закрывает пункт бенчмарка «старую ссылку не удалять, а
заморозить как read-only источник» — она остаётся видимой в истории.

Backfill: у каждого ученика с известным `academic_year` текущее состояние
становится снимком за этот год.

env.py без target_metadata → миграция вручную (op.execute).

Revision ID: 0007_student_year_history
Revises: 0006_quarter_academic_year
Create Date: 2026-09-04
"""
from alembic import op

revision = "0007_student_year_history"
down_revision = "0006_quarter_academic_year"
branch_labels = None
depends_on = None

_CREATE = """
CREATE TABLE student_years (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL REFERENCES students(id),
    academic_year integer NOT NULL,
    display_name text,
    spreadsheet_id text,
    updated_at timestamp DEFAULT (now() at time zone 'utc'),
    UNIQUE(student_id, academic_year)
);
CREATE INDEX idx_student_years_student ON student_years(student_id, academic_year DESC);
"""

BACKFILL_SQL = """
INSERT INTO student_years (student_id, academic_year, display_name, spreadsheet_id)
SELECT id, academic_year, display_name, spreadsheet_id
  FROM students
 WHERE academic_year IS NOT NULL
ON CONFLICT (student_id, academic_year) DO NOTHING
"""


def upgrade():
    op.execute(_CREATE)
    op.execute(BACKFILL_SQL)


def downgrade():
    op.execute("DROP TABLE IF EXISTS student_years")
