"""Smoke-проверка слоя подключения src/db/pg.py против реального PostgreSQL.

Проверяет ключевые отличия от sqlite, на которых держится миграция:
  • пул + контекст-менеджер (commit-on-exit, rollback-on-error);
  • плейсхолдеры %s; INSERT ... RETURNING (вместо lastrowid);
  • BIGINT (Telegram-id > 2^31, что переполнило бы 32-битный PG INTEGER);
  • Row с двойным доступом (row['c'] И row[0]) + dict(row);
  • маппинг UniqueViolation (бывш. sqlite3.IntegrityError).

Запуск: DATABASE_URL=... python scripts/pg_smoke.py
"""
import sys

from src.db.pg import Row, UniqueViolation, get_db_connection

BIG = 9_999_999_999  # > 2^31-1 (2_147_483_647): провалилось бы на INTEGER

with get_db_connection() as conn:
    cur = conn.cursor()
    cur.execute("DROP TABLE IF EXISTS _gs_smoke")
    cur.execute(
        "CREATE TABLE _gs_smoke ("
        " id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " name text UNIQUE NOT NULL,"
        " tg_id bigint,"
        " created_at timestamp DEFAULT (now() at time zone 'utc'))"
    )

with get_db_connection() as conn:
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO _gs_smoke (name, tg_id) VALUES (%s, %s) RETURNING id",
        ("alice", BIG),
    )
    new_id = cur.fetchone()[0]
    print(f"[ok] INSERT ... RETURNING id -> {new_id}")

with get_db_connection() as conn:
    cur = conn.cursor()
    cur.execute("SELECT id, name, tg_id FROM _gs_smoke WHERE name = %s", ("alice",))
    row = cur.fetchone()
    assert isinstance(row, Row), type(row)
    assert row["name"] == "alice", row["name"]          # доступ по имени
    assert row[1] == "alice", row[1]                    # доступ по индексу
    assert row["tg_id"] == BIG, row["tg_id"]            # BIGINT не переполнен
    assert dict(row) == {"id": new_id, "name": "alice", "tg_id": BIG}, dict(row)
    print(f"[ok] Row dual-access + dict(row): {dict(row)}")

# UniqueViolation маппинг + rollback (транзакция отката не валит пул)
try:
    with get_db_connection() as conn:
        conn.cursor().execute(
            "INSERT INTO _gs_smoke (name, tg_id) VALUES (%s, %s)", ("alice", 1)
        )
    print("[FAIL] ожидался UniqueViolation на дубле name")
    sys.exit(1)
except UniqueViolation:
    print("[ok] UniqueViolation поймана (бывш. sqlite3.IntegrityError)")

# Пул жив после отката — следующая операция работает
with get_db_connection() as conn:
    cur = conn.cursor()
    cur.execute("SELECT count(*) AS c FROM _gs_smoke")
    assert cur.fetchone()["c"] == 1
    cur.execute("DROP TABLE _gs_smoke")

print("SMOKE PASS")
