name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main # Запуск происходит при пуше в эту ветку

jobs:
  deploy:
    runs-on: self-hosted # Команда GitHub'у использовать твою малину

    steps:
      - name: Очистка старых root-файлов базы перед checkout
        run: |
          sudo rm -rf data/ || true
          sudo rm -rf config/ || true

      - name: Перенос файлов репозитория
        uses: actions/checkout@v4

      - name: Создание конфигурационных файлов из секретов
        run: |
          # Создаем .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
          echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
          
          # Создаем папку config (если её нет)
          mkdir -p config
          
          # Записываем JSON-ключ Google Sheets в файл напрямую из секрета
          echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > config/credentials.json

      - name: Сборка и перезапуск Docker

        run: |
          docker compose down || true
          docker compose up -d --build
